// Code generated by protoc-gen-go. DO NOT EDIT.
// source: player.proto

package player

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PlayerData struct {
	RoleInfo             *RoleInfo `protobuf:"bytes,1,opt,name=roleInfo,proto3" json:"roleInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PlayerData) Reset()         { *m = PlayerData{} }
func (m *PlayerData) String() string { return proto.CompactTextString(m) }
func (*PlayerData) ProtoMessage()    {}
func (*PlayerData) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{0}
}

func (m *PlayerData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerData.Unmarshal(m, b)
}
func (m *PlayerData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerData.Marshal(b, m, deterministic)
}
func (m *PlayerData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerData.Merge(m, src)
}
func (m *PlayerData) XXX_Size() int {
	return xxx_messageInfo_PlayerData.Size(m)
}
func (m *PlayerData) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerData.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerData proto.InternalMessageInfo

func (m *PlayerData) GetRoleInfo() *RoleInfo {
	if m != nil {
		return m.RoleInfo
	}
	return nil
}

type RoleInfo struct {
	Name                 string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32            `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	States               map[int32]string `protobuf:"bytes,3,rep,name=states,proto3" json:"states,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Fixcode              int32            `protobuf:"varint,4,opt,name=fixcode,proto3" json:"fixcode,omitempty"`
	Temp                 string           `protobuf:"bytes,6,opt,name=temp,proto3" json:"temp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RoleInfo) Reset()         { *m = RoleInfo{} }
func (m *RoleInfo) String() string { return proto.CompactTextString(m) }
func (*RoleInfo) ProtoMessage()    {}
func (*RoleInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{1}
}

func (m *RoleInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleInfo.Unmarshal(m, b)
}
func (m *RoleInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleInfo.Marshal(b, m, deterministic)
}
func (m *RoleInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleInfo.Merge(m, src)
}
func (m *RoleInfo) XXX_Size() int {
	return xxx_messageInfo_RoleInfo.Size(m)
}
func (m *RoleInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoleInfo proto.InternalMessageInfo

func (m *RoleInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RoleInfo) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *RoleInfo) GetStates() map[int32]string {
	if m != nil {
		return m.States
	}
	return nil
}

func (m *RoleInfo) GetFixcode() int32 {
	if m != nil {
		return m.Fixcode
	}
	return 0
}

func (m *RoleInfo) GetTemp() string {
	if m != nil {
		return m.Temp
	}
	return ""
}

func init() {
	proto.RegisterType((*PlayerData)(nil), "playerData")
	proto.RegisterType((*RoleInfo)(nil), "roleInfo")
	proto.RegisterMapType((map[int32]string)(nil), "roleInfo.StatesEntry")
}

func init() { proto.RegisterFile("player.proto", fileDescriptor_41d803d1b635d5c6) }

var fileDescriptor_41d803d1b635d5c6 = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0xc8, 0x49, 0xac,
	0x4c, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x32, 0xe6, 0xe2, 0x82, 0xf0, 0x5d, 0x12,
	0x4b, 0x12, 0x85, 0x54, 0xb9, 0x38, 0x8a, 0xf2, 0x73, 0x52, 0x3d, 0xf3, 0xd2, 0xf2, 0x25, 0x18,
	0x15, 0x18, 0x35, 0xb8, 0x8d, 0x38, 0xf5, 0x60, 0x02, 0x41, 0x70, 0x29, 0xa5, 0x13, 0x8c, 0x08,
	0x75, 0x42, 0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x60, 0xf5, 0x9c, 0x41, 0x60, 0xb6, 0x90,
	0x00, 0x17, 0x73, 0x62, 0x7a, 0xaa, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x6b, 0x10, 0x88, 0x29, 0xa4,
	0xcb, 0xc5, 0x56, 0x5c, 0x92, 0x58, 0x92, 0x5a, 0x2c, 0xc1, 0xac, 0xc0, 0xac, 0xc1, 0x6d, 0x24,
	0x0a, 0x37, 0x57, 0x2f, 0x18, 0x2c, 0xee, 0x9a, 0x57, 0x52, 0x54, 0x19, 0x04, 0x55, 0x24, 0x24,
	0xc1, 0xc5, 0x9e, 0x96, 0x59, 0x91, 0x9c, 0x9f, 0x92, 0x2a, 0xc1, 0x02, 0x36, 0x04, 0xc6, 0x05,
	0x59, 0x57, 0x92, 0x9a, 0x5b, 0x20, 0xc1, 0x06, 0xb1, 0x0e, 0xc4, 0x96, 0xb2, 0xe4, 0xe2, 0x46,
	0x32, 0x04, 0x64, 0x7b, 0x76, 0x6a, 0x25, 0xd8, 0x41, 0xac, 0x41, 0x20, 0xa6, 0x90, 0x08, 0x17,
	0x6b, 0x59, 0x62, 0x4e, 0x29, 0xc4, 0x45, 0x9c, 0x41, 0x10, 0x8e, 0x15, 0x93, 0x05, 0x63, 0x12,
	0x1b, 0x38, 0x18, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x73, 0x9f, 0x28, 0xfc, 0x16, 0x01,
	0x00, 0x00,
}
